[phases.setup]
nixPkgs = ["python310", "gcc", "python310Packages.pip", "python310Packages.setuptools", "python310Packages.wheel", "postgresql", "libffi", "openssl"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "pip install gunicorn"
]

[phases.build]
cmds = [
  "source /opt/venv/bin/activate",
  "cd back",
  "python -m compileall xavier_back"
]

[start]
cmd = "source /opt/venv/bin/activate && cd back && gunicorn --bind 0.0.0.0:$PORT 'xavier_back.app:create_app()'"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "."
PATH = "/opt/venv/bin:${PATH}"
