services:
  - type: web
    name: xavierAIback
    env: python
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: GRPC_PYTHON_BUILD_SYSTEM_OPENSSL
        value: 1
      - key: GRPC_PYTHON_BUILD_WITH_CYTHON
        value: 1
      - key: PIP_NO_BUILD_ISOLATION
        value: 1
    buildFilter:
      paths:
        - requirements.txt
        - "**/*.py"
        - build.sh
